apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: microdemo
  labels:
    app: api-gateway

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      imagePullSecrets:
        - name: jfrog-secret   #  REQUIRED for JFrog

      containers:
        - name: api-gateway

          # Jenkins will replace this dynamically
          image: image_name

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
